// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwduh_A0wPj-Zvpr22HdzR8boRkCN-_kI',
    appId: '1:194538245814:web:95a5f69ba3ef15b3fba017',
    messagingSenderId: '194538245814',
    projectId: 'masterpart-39497',
    authDomain: 'masterpart-39497.firebaseapp.com',
    storageBucket: 'masterpart-39497.appspot.com',
    measurementId: 'G-6LS752SXTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFetLJfYg7r2ax8_zPtOeaH5A1cxinTu0',
    appId: '1:194538245814:android:8bbe7cb2ee30efddfba017',
    messagingSenderId: '194538245814',
    projectId: 'masterpart-39497',
    storageBucket: 'masterpart-39497.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8SXt0_vcD0OKLL7vpMYBRlUVMKc98HwI',
    appId: '1:194538245814:ios:57b543aace58b8f2fba017',
    messagingSenderId: '194538245814',
    projectId: 'masterpart-39497',
    storageBucket: 'masterpart-39497.appspot.com',
    iosBundleId: 'com.example.authModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8SXt0_vcD0OKLL7vpMYBRlUVMKc98HwI',
    appId: '1:194538245814:ios:57b543aace58b8f2fba017',
    messagingSenderId: '194538245814',
    projectId: 'masterpart-39497',
    storageBucket: 'masterpart-39497.appspot.com',
    iosBundleId: 'com.example.authModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwduh_A0wPj-Zvpr22HdzR8boRkCN-_kI',
    appId: '1:194538245814:web:bab7afee51778c03fba017',
    messagingSenderId: '194538245814',
    projectId: 'masterpart-39497',
    authDomain: 'masterpart-39497.firebaseapp.com',
    storageBucket: 'masterpart-39497.appspot.com',
    measurementId: 'G-1X9E49PBG8',
  );
}
